name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run Lint
        run: pnpm run lint
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run Test
        run: pnpm run test:run
      - name: coverage
        run: pnpm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
